# Generated by Django 5.0.3 on 2024-03-25 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=150, unique=True, verbose_name="Nombre"
                    ),
                ),
            ],
            options={
                "verbose_name": "Categoria",
                "verbose_name_plural": "Categorias",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=150, unique=True, verbose_name="Nombre"
                    ),
                ),
                ("stock", models.IntegerField(default=0, verbose_name="Stock")),
                (
                    "pvp",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=9,
                        verbose_name="Precio Venta",
                    ),
                ),
                (
                    "precio",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=9,
                        verbose_name="Precio Compra",
                    ),
                ),
                (
                    "cat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="erp.category",
                        verbose_name="Categoría",
                    ),
                ),
            ],
            options={
                "verbose_name": "Producto",
                "verbose_name_plural": "Productos",
                "ordering": ["id"],
            },
        ),
    ]
