# Generated by Django 5.0.3 on 2024-03-25 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0002_rename_product_replacement"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="replacement",
            options={
                "ordering": ["id"],
                "verbose_name": "Repuestos",
                "verbose_name_plural": "Repuestos",
            },
        ),
    ]
