# Generated by Django 5.0.3 on 2024-03-25 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0003_alter_replacement_options"),
    ]

    operations = [
        migrations.RenameField(
            model_name="replacement",
            old_name="pvp",
            new_name="precio_venhta",
        ),
        migrations.RemoveField(
            model_name="replacement",
            name="precio",
        ),
    ]
