# Generated by Django 5.0.3 on 2024-03-25 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0004_rename_pvp_replacement_precio_venhta_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="replacement",
            old_name="precio_venhta",
            new_name="precio_venta",
        ),
        migrations.RemoveField(
            model_name="replacement",
            name="cat",
        ),
    ]
