# Generated by Django 5.0.3 on 2024-03-25 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0005_rename_precio_venhta_replacement_precio_venta_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="replacement",
            name="code_replacement",
            field=models.CharField(
                default=5, max_length=150, unique=True, verbose_name="Nombre"
            ),
            preserve_default=False,
        ),
    ]
