# Generated by Django 5.0.3 on 2024-03-25 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0007_remove_replacement_precio_venta"),
    ]

    operations = [
        migrations.AddField(
            model_name="replacement",
            name="cat",
            field=models.ForeignKey(
                default=7,
                on_delete=django.db.models.deletion.PROTECT,
                to="erp.category",
                verbose_name="Categoría",
            ),
            preserve_default=False,
        ),
    ]
