# Generated by Django 5.0.3 on 2024-03-26 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0009_alter_replacement_code_replacement_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="replacement",
            name="location",
            field=models.CharField(
                blank=True,
                max_length=150,
                null=True,
                unique=True,
                verbose_name="Ubicación",
            ),
        ),
    ]
