# Generated by Django 5.0.3 on 2024-03-26 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0010_replacement_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="replacement",
            name="location",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="Ubicación"
            ),
        ),
    ]
