# Generated by Django 5.0.3 on 2024-03-26 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0013_client"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Client",
            new_name="Customer",
        ),
    ]
