# Generated by Django 5.0.3 on 2024-03-26 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0014_rename_client_customer"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customer",
            old_name="names",
            new_name="name",
        ),
    ]
