# Generated by Django 5.0.3 on 2024-03-26 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0015_rename_names_customer_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customer",
            old_name="name",
            new_name="names",
        ),
    ]
