# Generated by Django 5.0.3 on 2024-03-26 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0016_rename_name_customer_names"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customer",
            old_name="names",
            new_name="name_company",
        ),
    ]
