# Generated by Django 5.0.3 on 2024-03-26 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0017_rename_names_customer_name_company"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="name_company",
        ),
        migrations.AddField(
            model_name="customer",
            name="name",
            field=models.CharField(
                default=17, max_length=150, unique=True, verbose_name="Cliente"
            ),
            preserve_default=False,
        ),
    ]
