# Generated by Django 5.0.3 on 2024-03-26 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0018_remove_customer_name_company_customer_name"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Customer",
            new_name="Clients",
        ),
    ]
