# Generated by Django 5.0.3 on 2024-03-26 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0020_brain_brand"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Brain",
        ),
    ]
