# Generated by Django 5.0.3 on 2024-03-27 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0021_delete_brain"),
    ]

    operations = [
        migrations.AddField(
            model_name="replacement",
            name="pvp",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=9, verbose_name="Precio Venta"
            ),
        ),
    ]
