# Generated by Django 5.0.3 on 2024-03-27 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0022_replacement_pvp"),
    ]

    operations = [
        migrations.AddField(
            model_name="replacement",
            name="precio_compra",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=9,
                verbose_name="Precio Compra",
            ),
        ),
    ]
