# Generated by Django 5.0.3 on 2024-03-27 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0023_replacement_precio_compra"),
    ]

    operations = [
        migrations.AddField(
            model_name="replacement",
            name="procentaje",
            field=models.DecimalField(
                decimal_places=2,
                default=1.4,
                max_digits=9,
                verbose_name="Precio Compra",
            ),
        ),
    ]
