# Generated by Django 5.0.3 on 2024-03-27 15:14

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0027_alter_replacement_pvp"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_joined",
                    models.DateField(
                        default=datetime.datetime.now, verbose_name="Fecha Venta"
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
                ),
                (
                    "iva",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
                ),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
                ),
                (
                    "cli",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="erp.clients",
                        verbose_name="Cliente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Venta",
                "verbose_name_plural": "Ventas",
                "ordering": ["id"],
            },
        ),
    ]
