# Generated by Django 5.0.3 on 2024-03-27 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0028_sale"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="replacement",
            name="procentaje",
        ),
    ]
