# Generated by Django 5.0.3 on 2024-03-28 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0029_remove_replacement_procentaje"),
    ]

    operations = [
        migrations.AlterField(
            model_name="replacement",
            name="precio_compra",
            field=models.DecimalField(
                decimal_places=0,
                default=0.0,
                max_digits=9,
                verbose_name="Precio Compra",
            ),
        ),
    ]
