# Generated by Django 5.0.3 on 2024-03-28 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0031_alter_replacement_precio_compra"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="replacement",
            name="precio_compra",
        ),
    ]
