# Generated by Django 5.0.3 on 2024-04-01 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0033_alter_replacement_stock"),
    ]

    operations = [
        migrations.RenameField(
            model_name="clients",
            old_name="name",
            new_name="names",
        ),
    ]
