# Generated by Django 5.0.3 on 2024-04-01 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0035_rename_names_clients_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sale",
            old_name="cli",
            new_name="name_cli",
        ),
    ]
