# Generated by Django 5.0.3 on 2024-04-01 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0036_rename_cli_sale_name_cli"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sale",
            old_name="name_cli",
            new_name="cli",
        ),
    ]
