# Generated by Django 5.0.3 on 2024-04-01 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0037_rename_name_cli_sale_cli"),
    ]

    operations = [
        migrations.CreateModel(
            name="DetSale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=0,
                        default=0.0,
                        max_digits=9,
                        verbose_name="Precio",
                    ),
                ),
                ("cant", models.IntegerField(default=0, verbose_name="Cantidad")),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
                ),
                (
                    "prod",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="erp.replacement",
                        verbose_name="Repuesto(s)",
                    ),
                ),
                (
                    "sale",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="erp.sale",
                        verbose_name="Venta",
                    ),
                ),
            ],
            options={
                "verbose_name": "Detalle de Venta",
                "verbose_name_plural": "Detalle de Ventas",
                "ordering": ["id"],
            },
        ),
    ]
