# Generated by Django 5.0.3 on 2024-04-01 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0038_detsale"),
    ]

    operations = [
        migrations.RenameField(
            model_name="detsale",
            old_name="prod",
            new_name="replacement",
        ),
    ]
