# Generated by Django 5.0.3 on 2024-04-01 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0039_rename_prod_detsale_replacement"),
    ]

    operations = [
        migrations.CreateModel(
            name="PayMethods",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=150, unique=True, verbose_name="Método de Pago"
                    ),
                ),
            ],
        ),
    ]
