# Generated by Django 5.0.3 on 2024-04-01 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0041_sale_pay_method"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="paymethods",
            options={
                "ordering": ["id"],
                "verbose_name": "Metodo de Pago",
                "verbose_name_plural": "Metodos de Pago",
            },
        ),
    ]
