# Generated by Django 5.0.3 on 2024-04-01 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0042_alter_paymethods_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="detsale",
            name="pay_method",
            field=models.ForeignKey(
                default=42,
                on_delete=django.db.models.deletion.CASCADE,
                to="erp.paymethods",
                verbose_name="Medio de Pago",
            ),
            preserve_default=False,
        ),
    ]
