# Generated by Django 5.0.3 on 2024-04-01 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0043_detsale_pay_method"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="detsale",
            name="pay_method",
        ),
    ]
