# Generated by Django 5.0.3 on 2024-04-02 14:10

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0044_remove_detsale_pay_method"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cotizacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_joined",
                    models.DateField(
                        default=datetime.datetime.now, verbose_name="Fecha Venta"
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
                ),
                (
                    "iva",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
                ),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
                ),
                (
                    "cli",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="erp.clients",
                        verbose_name="Cliente",
                    ),
                ),
                (
                    "pay_method",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="erp.paymethods",
                        verbose_name="Método de Pago",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cotización",
                "verbose_name_plural": "Cotizaciones",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="DetCotizacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=0,
                        default=0.0,
                        max_digits=9,
                        verbose_name="Precio",
                    ),
                ),
                ("cant", models.IntegerField(default=0, verbose_name="Cantidad")),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
                ),
                (
                    "replacement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="erp.replacement",
                        verbose_name="Repuesto(s)",
                    ),
                ),
                (
                    "sale",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="erp.cotizacion",
                        verbose_name="Venta",
                    ),
                ),
            ],
            options={
                "verbose_name": "Detalle Cotización",
                "verbose_name_plural": "Detalle Cotizaciones",
                "ordering": ["id"],
            },
        ),
    ]
