# Generated by Django 5.0.3 on 2024-04-02 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0046_detsale_pay_method"),
    ]

    operations = [
        migrations.AlterField(
            model_name="detsale",
            name="subtotal",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=9, verbose_name="Cantidad"
            ),
        ),
    ]
