# Generated by Django 5.0.3 on 2024-04-02 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0049_rename_cant_detsale_stock"),
    ]

    operations = [
        migrations.RenameField(
            model_name="detsale",
            old_name="stock",
            new_name="cant",
        ),
    ]
