# Generated by Django 5.0.3 on 2024-04-02 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0051_rename_stock_replacement_cant"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="detcotizacion",
            name="sale",
        ),
        migrations.RemoveField(
            model_name="detcotizacion",
            name="replacement",
        ),
        migrations.DeleteModel(
            name="Cotizacion",
        ),
        migrations.DeleteModel(
            name="DetCotizacion",
        ),
    ]
