# Generated by Django 5.0.3 on 2024-04-03 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0052_remove_detcotizacion_sale_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Money",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=150, unique=True, verbose_name="Tipo Moneda"
                    ),
                ),
            ],
            options={
                "verbose_name": "Moneda",
                "verbose_name_plural": "Monedas",
                "ordering": ["id"],
            },
        ),
        migrations.RenameModel(
            old_name="Sale",
            new_name="Cotizacion",
        ),
        migrations.AlterModelOptions(
            name="cotizacion",
            options={
                "ordering": ["id"],
                "verbose_name": "Cotización",
                "verbose_name_plural": "Cotizaciones",
            },
        ),
        migrations.DeleteModel(
            name="DetSale",
        ),
    ]
