# Generated by Django 5.0.3 on 2024-04-04 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0055_alter_detcotizacion_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="detcotizacion",
            old_name="cant",
            new_name="stock",
        ),
    ]
