# Generated by Django 5.0.3 on 2024-04-04 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0057_rename_stock_detcotizacion_cant"),
    ]

    operations = [
        migrations.RenameField(
            model_name="detcotizacion",
            old_name="cant",
            new_name="stock",
        ),
        migrations.RenameField(
            model_name="replacement",
            old_name="cant",
            new_name="stock",
        ),
    ]
