# Generated by Django 5.0.3 on 2024-04-04 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0058_rename_cant_detcotizacion_stock_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="detcotizacion",
            old_name="sale",
            new_name="cotizacion",
        ),
    ]
