# Generated by Django 5.0.4 on 2024-04-10 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0059_rename_sale_detcotizacion_cotizacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replacement',
            name='name',
            field=models.CharField(max_length=150, null=True, verbose_name='Nombre'),
        ),
    ]
