# Generated by Django 5.0.4 on 2024-04-10 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0060_alter_replacement_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlazoEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Plazo Entrega')),
            ],
            options={
                'verbose_name': 'Plazo Entrega',
                'verbose_name_plural': 'Plazos Entrega',
                'ordering': ['id'],
            },
        ),
    ]
